// examples/svelte-kit-example/src/routes/dashboard/+page.svelte
<script>
import { client } from "$lib/feature-client";

const session = client.useSession();
</script>

<Card.Root class="w-[350px]">
  <Card.Header>
    <Card.Title>User</Card.Title>
    <Card.Description>Welcome to the dashboard</Card.Description>
  </Card.Header>
  <Card.Content>
    <div class="flex items-center gap-2">
      <Avatar.Root>
        <Avatar.Image src={$session.data?.user.image} />
        <Avatar.Fallback>
          {$session.data?.user.name[0]}
        </Avatar.Fallback>
      </Avatar.Root>
      <div class="">
        <h3 class="text-sm">
          {$session.data?.user.name}
        </h3>
        <p class="text-xs text-muted-foreground">
          {$session.data?.user.email}
        </p>
      </div>
    </div>
  </Card.Content>
  <Card.Footer>
    <Button
      variant="outline"
      on:click={() => {
        client.signOut({
          fetchOptions: {
            body: {
              callbackURL: "/",
            },
          },
        });
      }}>Sign Out</Button
    >
  </Card.Footer>
</Card.Root>

// examples/nuxt-example/pages/dashboard.vue
<script setup lang="ts">
import { useSession } from "~/lib/feature-client";
const { data: session } = await useSession(useFetch);
</script>


<template>
    <div class="min-h-[80vh] flex items-center justify-center overflow-hidden no-visible-scrollbar px-6 md:px-0">
        <Card class="w-[350px]">
            <CardHeader>
                <CardTitle>
                    User
                </CardTitle>
            </CardHeader>
            <CardContent>
                <div class="flex gap-2 items-center">
                    <Avatar>
                        <AvatarImage :src="session?.user.image || ''" alt="User profile" />
                        <AvatarFallback>{{ session?.user.name[0] }}</AvatarFallback>
                    </Avatar>
                    <div>
                        <p class="text-sm">
                            {{ session?.user?.name }}
                        </p>
                        <p class="text-xs">
                            {{ session?.user?.email }}
                        </p>
                    </div>
                </div>
            </CardContent>
            <CardFooter>
                <Button @click="async () => {
                    await signOut()
                    // router.push('/')
                }" variant="secondary">
                    Sing Out
                </Button>
            </CardFooter>
        </Card>
    </div>
</template>
